spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_ati
spring.datasource.username=gestao_user
spring.datasource.password=gestao123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


server.port=8080
spring.application.name=gestao-ati
spring.jpa.open-in-view=false

jwt.secret=chave-super-secreta-gestao-ati-2024-deve-ter-256-bits-minimo
jwt.expiration=86400000

springdoc.enable-hateoas=false